CREATE DATABASE IF NOT EXISTS SchemaTest;

USE SchemaTest;

-- USER 
CREATE TABLE IF NOT EXISTS User(
    Id              VARCHAR(36) PRIMARY KEY NOT NULL,
    UserName        VARCHAR(80),
    Role            VARCHAR(50)
);

-- TRUNCATE ALL TABLES
DELIMITER //
CREATE PROCEDURE TruncateAllTables()
BEGIN
    SET FOREIGN_KEY_CHECKS = 0;
    TRUNCATE TABLE User;
    SET FOREIGN_KEY_CHECKS = 1;
END //
DELIMITER ;